# Generated by Django 6.0.8 on 2026-09-13 07:47

import django.db.models.deletion
import insurance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(default=insurance.models.customer_id, max_length=20, unique=True)),
                ('national_id', models.CharField(max_length=30, unique=True)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(db_index=True, max_length=30)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=insurance.models.order_id, max_length=20, unique=True)),
                ('selected_offer_id', models.CharField(max_length=20)),
                ('offer_snapshot', models.JSONField()),
                ('premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='PENDING_PAYMENT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(default=insurance.models.invoice_id, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('status', models.CharField(default='UNPAID', max_length=20)),
                ('payment_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='insurance.order')),
            ],
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='insurance.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(default=insurance.models.payment_id, max_length=20, unique=True)),
                ('status', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='insurance.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(default=insurance.models.policy_id, max_length=20, unique=True)),
                ('policy_number', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deductible', models.DecimalField(decimal_places=2, max_digits=12)),
                ('document_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='policy', to='insurance.order')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.CharField(default=insurance.models.quote_id, max_length=20, unique=True)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('selected_offer_id', models.CharField(blank=True, max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.customer')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.quote'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(default=insurance.models.offer_id, max_length=20, unique=True)),
                ('provider', models.CharField(default='Mock Concord', max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deductible', models.DecimalField(decimal_places=2, max_digits=12)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='insurance.quote')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(default=insurance.models.vehicle_id, max_length=20, unique=True)),
                ('registration_type', models.CharField(max_length=30)),
                ('plate_no', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('vehicle_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='insurance.customer')),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.vehicle'),
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.vehicle'),
        ),
    ]
